cc_library(
    name = "CCLib",
    hdrs = ["q.h"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "q",
    srcs = [
        "q.cc",
    ],
    deps = [
        ":CCLib",
    ],
)
